name: IamCI

on: 
  push:
    branchs:  # 修正拼写错误：branchs → branches
      - '*'
  pull_request:
    types: [opened, reopened]

jobs:
  iamci:
    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: iamci

    strategy:
      matrix:
        go_version: ['1.22']  # 建议版本号加引号
        os: [ubuntu-latest]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4  # 升级到最新版
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code
        uses: actions/checkout@v4  # 升级到最新版

      - name: Run go modules tidy
        run: make tidy

      - name: Generate files
        run: make gen

      - name: Lint check
        run: make lint

      - name: Unit test with coverage
        run: make cover

      - name: Build for host platform
        run: make build

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4  # 关键升级：v1 → v4
        with:
          name: coverage-report
          path: _output/coverage.out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 升级到 v2

      - name: Login to DockerHub
        uses: docker/login-action@v2  # 升级到 v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: make push